### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by mathanamathav**

### CODE REVIEW

**Comment by drMy5tery** [comment]
image

@mathanamathav Video view container still needs some rework 

image

**Comment by mathanamathav** [comment]
image

is this okay then @drMy5tery

**Comment by mathanamathav** [comment]
Screenshot 2023-05-26 103147
?

**Comment by drMy5tery** [comment]
@mathanamathav The 2nd one looks good and try to increase the border-radius slightly (ig 20px would be fine) & for the colour of the border,try to use any dim colour which would be suitable there.
Also the distance between each text(video name,channel name info bar(likes,cmnts etc..)) would look nice if it's evenly distributed.

**Comment by mathanamathav** [comment]
we went the border orange because it fits the theme of line and comments icon color
image

image

**Comment by mathanamathav** [comment]
first one without the any color looks nice @drMy5tery

**Comment by drMy5tery** [comment]
@mathanamathav then we can gi with that

**Comment by drMy5tery** [comment]
@mathanamathav Shall we merge this branch?

**Comment by mathanamathav** [comment]
Yeah change the description link on the main page since you changed ut

**Comment by drMy5tery** [comment]
Merging after debugging painnn

**Pull request merged**
