### PR TITLE
count with suffix is and loading animation added

### PR DESCRIPTION
**Pull request by drMy5tery**
result container needs to be flexible and dynamic based on the result generated ,Validations and some further UI changes and enhancements are needed to be done. @mathanamathav

### CODE REVIEW

**Comment by mathanamathav** [comment]
image

was above commit working in your local?

**Comment by mathanamathav** [comment]
> image
> 
> was above commit working in your local?

nvm fixed this one!

**Review by mathanamathav — APPROVED** [review]
LGTM with minor fixes!!

**Comment by drMy5tery** [comment]
Nice

**Pull request closed without merging**
